FROM microsoft/aspnetcore-build AS builder
WORKDIR /source

# Copy csproj and restore as distinct layers
COPY ./../src/*.sln ./
RUN dotnet restore

# Copy everything else and build
COPY ./../src ./
RUN dotnet publish --output /app/

# Default Environment
ENV ASPNETCORE_ENVIRONMENT="Development"

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "Camaleao.Api.dll"]